export const COLORS = {
	STICKER_BACKGROUND: '#ffd670',
	FLIPPED_CARD_FRONT_BACKGROUND: '#70d6ff',
	FLIPPED_CARD_BACK_BACKGROUND: '#ff70a6',
	SWITCH_BLOCK: '#F79327',
	FONT: '#000',
	SELECTION: '#3a86ff',
	GRID: '#d2d6db',
};
